image: Visual Studio 2017

assembly_info:
  patch: false

configuration: Release

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /nofetch /b $env:APPVEYOR_REPO_BRANCH

build_script:
  - cmd: dotnet build Usenet.sln --configuration %CONFIGURATION% --no-restore
  
test_script:
  - cmd: dotnet test test/UsenetTests/UsenetTests.csproj

after_build:
  - cmd: nuget pack src/Usenet/Usenet.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Usenet.%GitVersion_NuGetVersion%.nupkg"
