image: Visual Studio 2017

assembly_info:
  patch: false

configuration: Release

build_script:
  - ps: dotnet --version
  - ps: dotnet restore
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /nofetch /b $env:APPVEYOR_REPO_BRANCH
  - ps: dotnet build Usenet.sln --configuration $env:CONFIGURATION --no-restore
  - ps: dotnet test test/UsenetTests/UsenetTests.csproj --no-build --no-restore
  - ps: dotnet pack src/Usenet/Usenet.csproj --output . --no-build --no-restore --configuration $env:CONFIGURATION -p:version=$env:GitVersion_NuGetVersion
  #- ps: appveyor PushArtifact "src/Usenet/Usenet.$env:GitVersion_NuGetVersion.nupkg"
  #- ps: nuget push "src/Usenet/Usenet.$env:GitVersion_NuGetVersion.nupkg" -ApiKey  -Source https://ci.appveyor.com/nuget/keimpema/api/v2/package

deploy:
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/keimpema/api/v2/package
    api_key:
      secure: kdR0ezKgvtAqExn/40WQ1gKKQ2v3r0UfqgahpsO2jAs=
    skip_symbols: false
    symbol_server: https://ci.appveyor.com/nuget/keimpema/api/v2/package
    artifact: src/Usenet/*.nupkg
    on:
      APPVEYOR_REPO_TAG: false

  - provider: NuGet
    server: https://ci.appveyor.com/nuget/keimpema/api/v2/package
    api_key:
      secure: kdR0ezKgvtAqExn/40WQ1gKKQ2v3r0UfqgahpsO2jAs=
    skip_symbols: false
    symbol_server: https://ci.appveyor.com/nuget/keimpema/api/v2/package
    artifact: src/Usenet/*.nupkg
    on:
      APPVEYOR_REPO_TAG: true
