image: Visual Studio 2017

assembly_info:
  patch: false

before_build:
  - cmd: dotnet restore
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

build:
  project: Usenet.sln

after_build:
  - cmd: ECHO nuget pack **/Usenet.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack **/Usenet.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Usenet.%GitVersion_NuGetVersion%.nupkg"
