image: Visual Studio 2017

assembly_info:
  patch: false

configuration: Release

build_script:
  - ps: dotnet --version
  - ps: dotnet restore
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /nofetch /b $env:APPVEYOR_REPO_BRANCH
  - ps: dotnet build Usenet.sln --configuration $env:CONFIGURATION --no-restore
  - ps: dotnet test test/UsenetTests/UsenetTests.csproj --no-build --no-restore
  - ps: dotnet pack src/Usenet/Usenet.csproj --no-build --no-restore --configuration $env:CONFIGURATION -p:version=$env:GitVersion_NuGetVersion
  - ps: appveyor PushArtifact "Usenet.$env:GitVersion_NuGetVersion.nupkg"
